import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        backgroundColor:'#19C3FB',
        alignItems:'center',
    },
    dateText:{
        fontSize:16,
        color:'#ffffff99',
        marginVertical:10
    },
    cityText:{
        fontSize:26,
        color:'#ffffff'
    },
    countryTxt:{
        color:'#ffffff99',
        marginVertical:10
    },
    temp:{
        fontSize:60,
        color:'#ffffff'
    },
    downArrow:{
        width:15,
        height:15,
        tintColor:'#ffffff99',
    },
    upArrow:{
        width:15,
        height:15,
        transform:[{rotate:'180deg'}],
        tintColor:'#ffffff99',
        marginLeft:10
    },
    subContainer:{
        width:'100%',
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center'
    },
    feelsTxt:{
        color:'#ffffff99',
        fontSize:12,
        marginVertical:5
    },
    degTxt:{
        color:'#ffffff',
        fontSize:16,
    },
    arrowBox:{
        flexDirection:'row',
        alignItems:'center',
    },
    tempContainer:{
        width:'40%',
        alignItems:'center'
    },
    bottomContainer:{
        width:'100%',
        alignItems:'center',
        marginVertical:10
    },
    messageTxt:{
        color:'#ffffff',
        fontSize:25,
        fontWeight:'bold',
        marginVertical:15
    },
    timeList:{
        width:'100%',
        borderColor:'#ffffff99',
        borderTopWidth:1,
        borderBottomWidth:1,
        height:90
    },
    listItem:{
        alignItems:'center',
        marginHorizontal:10,
        justifyContent:'space-evenly'
    },
    timeTxt:{
        color:'#ffffff99',
        fontSize:12,
        textAlign:'center'
    },
    tempTxt:{
        fontSize:20,
        color:'#ffffff',
        textAlign:'center'
    },
    timeContainer:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-evenly',
        marginVertical:10
    },
    infoItem:{
        marginHorizontal:5,
        width:100,
        height:40,
        marginVertical:15
    },
    infoTitle:{
        color:'#ffffff99',

    },
    infoVal:{
        color:'#ffffff',
        fontSize:20
    },
    weekItem:{
        flexDirection:'row',
        width:'100%',
        marginVertical:15,
        justifyContent:'space-evenly',
        alignItems:'center'
    },

})

export default styles;